version: 2026.4.{build}

#image: Visual Studio 2026
image: vs2026-master-gce-us-central1
build_cloud: bakery-gce-us-central1

dotnet_csproj:
  patch: true
  file: '**\*.*proj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

install: 
  - appveyor version
  
before_build:
  - dotnet restore AppVeyorBuildAgentTestSolution.sln
  
build:
  project: AppVeyorBuildAgentTestSolution.sln
  publish_aspnet_core: true
  parallel: true
  verbosity: quiet

test: off
